from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon.png'

# Colors
PRIMARY_COLOR = '#1e81b0'
PRIMERY_COLOR_DARKER = '#16658a'
PRIMARY_COLOR_DARKEST = '#115270'

# Sizing
FONT_SIZE_BIG = 40
FONT_SIZE_MEDIUN = 24
FONT_SIZE_SMALL = 19
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500
